//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_ClassMeeting_Attendance", "Attendance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Attendance), "ClassMeeting", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.ClassMeeting), true)]
[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_ClassMeeting_Calendar", "Calendar", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Calendar), "ClassMeeting", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.ClassMeeting), true)]
[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_ClassMeeting_Section", "Section", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Section), "ClassMeeting", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.ClassMeeting), true)]
[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_ClassMeeting_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Student), "ClassMeeting", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.ClassMeeting), true)]
[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_Registration_Section", "Section", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Section), "Registration", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.Registration), true)]
[assembly: EdmRelationshipAttribute("AttendanceModel", "FK_Registration_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AttendanceModel.Student), "Registration", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AttendanceModel.Registration), true)]

#endregion

namespace AttendanceModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AttendanceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AttendanceEntities object using the connection string found in the 'AttendanceEntities' section of the application configuration file.
        /// </summary>
        public AttendanceEntities() : base("name=AttendanceEntities", "AttendanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AttendanceEntities object.
        /// </summary>
        public AttendanceEntities(string connectionString) : base(connectionString, "AttendanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AttendanceEntities object.
        /// </summary>
        public AttendanceEntities(EntityConnection connection) : base(connection, "AttendanceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppUser> AppUsers
        {
            get
            {
                if ((_AppUsers == null))
                {
                    _AppUsers = base.CreateObjectSet<AppUser>("AppUsers");
                }
                return _AppUsers;
            }
        }
        private ObjectSet<AppUser> _AppUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attendance> Attendances
        {
            get
            {
                if ((_Attendances == null))
                {
                    _Attendances = base.CreateObjectSet<Attendance>("Attendances");
                }
                return _Attendances;
            }
        }
        private ObjectSet<Attendance> _Attendances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calendar> Calendars
        {
            get
            {
                if ((_Calendars == null))
                {
                    _Calendars = base.CreateObjectSet<Calendar>("Calendars");
                }
                return _Calendars;
            }
        }
        private ObjectSet<Calendar> _Calendars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassMeeting> ClassMeetings
        {
            get
            {
                if ((_ClassMeetings == null))
                {
                    _ClassMeetings = base.CreateObjectSet<ClassMeeting>("ClassMeetings");
                }
                return _ClassMeetings;
            }
        }
        private ObjectSet<ClassMeeting> _ClassMeetings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Registration> Registrations
        {
            get
            {
                if ((_Registrations == null))
                {
                    _Registrations = base.CreateObjectSet<Registration>("Registrations");
                }
                return _Registrations;
            }
        }
        private ObjectSet<Registration> _Registrations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Section> Sections
        {
            get
            {
                if ((_Sections == null))
                {
                    _Sections = base.CreateObjectSet<Section>("Sections");
                }
                return _Sections;
            }
        }
        private ObjectSet<Section> _Sections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppUsers(AppUser appUser)
        {
            base.AddObject("AppUsers", appUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attendances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttendances(Attendance attendance)
        {
            base.AddObject("Attendances", attendance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calendars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalendars(Calendar calendar)
        {
            base.AddObject("Calendars", calendar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassMeetings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassMeetings(ClassMeeting classMeeting)
        {
            base.AddObject("ClassMeetings", classMeeting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Registrations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistrations(Registration registration)
        {
            base.AddObject("Registrations", registration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSections(Section section)
        {
            base.AddObject("Sections", section);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="AppUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppUser object.
        /// </summary>
        /// <param name="appUserID">Initial value of the AppUserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="eMail">Initial value of the EMail property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static AppUser CreateAppUser(global::System.Int32 appUserID, global::System.String firstName, global::System.String lastName, global::System.String eMail, global::System.String password, global::System.DateTime createDate)
        {
            AppUser appUser = new AppUser();
            appUser.AppUserID = appUserID;
            appUser.FirstName = firstName;
            appUser.LastName = lastName;
            appUser.EMail = eMail;
            appUser.Password = password;
            appUser.CreateDate = createDate;
            return appUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppUserID
        {
            get
            {
                return _AppUserID;
            }
            set
            {
                if (_AppUserID != value)
                {
                    OnAppUserIDChanging(value);
                    ReportPropertyChanging("AppUserID");
                    _AppUserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppUserID");
                    OnAppUserIDChanged();
                }
            }
        }
        private global::System.Int32 _AppUserID;
        partial void OnAppUserIDChanging(global::System.Int32 value);
        partial void OnAppUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="Attendance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attendance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attendance object.
        /// </summary>
        /// <param name="attendanceID">Initial value of the AttendanceID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Attendance CreateAttendance(global::System.Int32 attendanceID, global::System.String name, global::System.DateTime createDate)
        {
            Attendance attendance = new Attendance();
            attendance.AttendanceID = attendanceID;
            attendance.Name = name;
            attendance.CreateDate = createDate;
            return attendance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttendanceID
        {
            get
            {
                return _AttendanceID;
            }
            set
            {
                if (_AttendanceID != value)
                {
                    OnAttendanceIDChanging(value);
                    ReportPropertyChanging("AttendanceID");
                    _AttendanceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AttendanceID");
                    OnAttendanceIDChanged();
                }
            }
        }
        private global::System.Int32 _AttendanceID;
        partial void OnAttendanceIDChanging(global::System.Int32 value);
        partial void OnAttendanceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Attendance", "ClassMeeting")]
        public EntityCollection<ClassMeeting> ClassMeetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Attendance", "ClassMeeting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Attendance", "ClassMeeting", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="Calendar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calendar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calendar object.
        /// </summary>
        /// <param name="calendarID">Initial value of the CalendarID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Calendar CreateCalendar(global::System.Int32 calendarID, global::System.DateTime date, global::System.DateTime createDate)
        {
            Calendar calendar = new Calendar();
            calendar.CalendarID = calendarID;
            calendar.Date = date;
            calendar.CreateDate = createDate;
            return calendar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CalendarID
        {
            get
            {
                return _CalendarID;
            }
            set
            {
                if (_CalendarID != value)
                {
                    OnCalendarIDChanging(value);
                    ReportPropertyChanging("CalendarID");
                    _CalendarID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CalendarID");
                    OnCalendarIDChanged();
                }
            }
        }
        private global::System.Int32 _CalendarID;
        partial void OnCalendarIDChanging(global::System.Int32 value);
        partial void OnCalendarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Calendar", "ClassMeeting")]
        public EntityCollection<ClassMeeting> ClassMeetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Calendar", "ClassMeeting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Calendar", "ClassMeeting", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="ClassMeeting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassMeeting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassMeeting object.
        /// </summary>
        /// <param name="classMeetingID">Initial value of the ClassMeetingID property.</param>
        /// <param name="calendarID">Initial value of the CalendarID property.</param>
        /// <param name="sectionID">Initial value of the SectionID property.</param>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="attendanceID">Initial value of the AttendanceID property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static ClassMeeting CreateClassMeeting(global::System.Int32 classMeetingID, global::System.Int32 calendarID, global::System.Int32 sectionID, global::System.Int32 studentID, global::System.Int32 attendanceID, global::System.DateTime createDate)
        {
            ClassMeeting classMeeting = new ClassMeeting();
            classMeeting.ClassMeetingID = classMeetingID;
            classMeeting.CalendarID = calendarID;
            classMeeting.SectionID = sectionID;
            classMeeting.StudentID = studentID;
            classMeeting.AttendanceID = attendanceID;
            classMeeting.CreateDate = createDate;
            return classMeeting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassMeetingID
        {
            get
            {
                return _ClassMeetingID;
            }
            set
            {
                if (_ClassMeetingID != value)
                {
                    OnClassMeetingIDChanging(value);
                    ReportPropertyChanging("ClassMeetingID");
                    _ClassMeetingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClassMeetingID");
                    OnClassMeetingIDChanged();
                }
            }
        }
        private global::System.Int32 _ClassMeetingID;
        partial void OnClassMeetingIDChanging(global::System.Int32 value);
        partial void OnClassMeetingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CalendarID
        {
            get
            {
                return _CalendarID;
            }
            set
            {
                OnCalendarIDChanging(value);
                ReportPropertyChanging("CalendarID");
                _CalendarID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CalendarID");
                OnCalendarIDChanged();
            }
        }
        private global::System.Int32 _CalendarID;
        partial void OnCalendarIDChanging(global::System.Int32 value);
        partial void OnCalendarIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                OnSectionIDChanging(value);
                ReportPropertyChanging("SectionID");
                _SectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionID");
                OnSectionIDChanged();
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttendanceID
        {
            get
            {
                return _AttendanceID;
            }
            set
            {
                OnAttendanceIDChanging(value);
                ReportPropertyChanging("AttendanceID");
                _AttendanceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttendanceID");
                OnAttendanceIDChanged();
            }
        }
        private global::System.Int32 _AttendanceID;
        partial void OnAttendanceIDChanging(global::System.Int32 value);
        partial void OnAttendanceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Attendance", "Attendance")]
        public Attendance Attendance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attendance>("AttendanceModel.FK_ClassMeeting_Attendance", "Attendance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attendance>("AttendanceModel.FK_ClassMeeting_Attendance", "Attendance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Attendance> AttendanceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attendance>("AttendanceModel.FK_ClassMeeting_Attendance", "Attendance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Attendance>("AttendanceModel.FK_ClassMeeting_Attendance", "Attendance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Calendar", "Calendar")]
        public Calendar Calendar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("AttendanceModel.FK_ClassMeeting_Calendar", "Calendar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("AttendanceModel.FK_ClassMeeting_Calendar", "Calendar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Calendar> CalendarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Calendar>("AttendanceModel.FK_ClassMeeting_Calendar", "Calendar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Calendar>("AttendanceModel.FK_ClassMeeting_Calendar", "Calendar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Section", "Section")]
        public Section Section
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_ClassMeeting_Section", "Section").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_ClassMeeting_Section", "Section").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Section> SectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_ClassMeeting_Section", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Section>("AttendanceModel.FK_ClassMeeting_Section", "Section", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_ClassMeeting_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_ClassMeeting_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_ClassMeeting_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("AttendanceModel.FK_ClassMeeting_Student", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="Registration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Registration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Registration object.
        /// </summary>
        /// <param name="registrationID">Initial value of the RegistrationID property.</param>
        /// <param name="sectionID">Initial value of the SectionID property.</param>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Registration CreateRegistration(global::System.Int32 registrationID, global::System.Int32 sectionID, global::System.Int32 studentID, global::System.DateTime createDate)
        {
            Registration registration = new Registration();
            registration.RegistrationID = registrationID;
            registration.SectionID = sectionID;
            registration.StudentID = studentID;
            registration.CreateDate = createDate;
            return registration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RegistrationID
        {
            get
            {
                return _RegistrationID;
            }
            set
            {
                if (_RegistrationID != value)
                {
                    OnRegistrationIDChanging(value);
                    ReportPropertyChanging("RegistrationID");
                    _RegistrationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegistrationID");
                    OnRegistrationIDChanged();
                }
            }
        }
        private global::System.Int32 _RegistrationID;
        partial void OnRegistrationIDChanging(global::System.Int32 value);
        partial void OnRegistrationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                OnSectionIDChanging(value);
                ReportPropertyChanging("SectionID");
                _SectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionID");
                OnSectionIDChanged();
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_Registration_Section", "Section")]
        public Section Section
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_Registration_Section", "Section").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_Registration_Section", "Section").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Section> SectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("AttendanceModel.FK_Registration_Section", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Section>("AttendanceModel.FK_Registration_Section", "Section", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_Registration_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_Registration_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_Registration_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("AttendanceModel.FK_Registration_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("AttendanceModel.FK_Registration_Student", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="Section")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Section : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="sectionID">Initial value of the SectionID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="creditHours">Initial value of the CreditHours property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Section CreateSection(global::System.Int32 sectionID, global::System.String name, global::System.Int32 creditHours, global::System.DateTime createDate)
        {
            Section section = new Section();
            section.SectionID = sectionID;
            section.Name = name;
            section.CreditHours = creditHours;
            section.CreateDate = createDate;
            return section;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionID
        {
            get
            {
                return _SectionID;
            }
            set
            {
                if (_SectionID != value)
                {
                    OnSectionIDChanging(value);
                    ReportPropertyChanging("SectionID");
                    _SectionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SectionID");
                    OnSectionIDChanged();
                }
            }
        }
        private global::System.Int32 _SectionID;
        partial void OnSectionIDChanging(global::System.Int32 value);
        partial void OnSectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreditHours
        {
            get
            {
                return _CreditHours;
            }
            set
            {
                OnCreditHoursChanging(value);
                ReportPropertyChanging("CreditHours");
                _CreditHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditHours");
                OnCreditHoursChanged();
            }
        }
        private global::System.Int32 _CreditHours;
        partial void OnCreditHoursChanging(global::System.Int32 value);
        partial void OnCreditHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Section", "ClassMeeting")]
        public EntityCollection<ClassMeeting> ClassMeetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Section", "ClassMeeting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Section", "ClassMeeting", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_Registration_Section", "Registration")]
        public EntityCollection<Registration> Registrations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Registration>("AttendanceModel.FK_Registration_Section", "Registration");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Registration>("AttendanceModel.FK_Registration_Section", "Registration", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AttendanceModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="scholarShip">Initial value of the ScholarShip property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Student CreateStudent(global::System.Int32 studentID, global::System.String firstName, global::System.String lastName, global::System.Decimal scholarShip, global::System.DateTime createDate)
        {
            Student student = new Student();
            student.StudentID = studentID;
            student.FirstName = firstName;
            student.LastName = lastName;
            student.ScholarShip = scholarShip;
            student.CreateDate = createDate;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                if (_StudentID != value)
                {
                    OnStudentIDChanging(value);
                    ReportPropertyChanging("StudentID");
                    _StudentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentID");
                    OnStudentIDChanged();
                }
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ScholarShip
        {
            get
            {
                return _ScholarShip;
            }
            set
            {
                OnScholarShipChanging(value);
                ReportPropertyChanging("ScholarShip");
                _ScholarShip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScholarShip");
                OnScholarShipChanged();
            }
        }
        private global::System.Decimal _ScholarShip;
        partial void OnScholarShipChanging(global::System.Decimal value);
        partial void OnScholarShipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Enrolled
        {
            get
            {
                return _Enrolled;
            }
            set
            {
                OnEnrolledChanging(value);
                ReportPropertyChanging("Enrolled");
                _Enrolled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enrolled");
                OnEnrolledChanged();
            }
        }
        private Nullable<global::System.DateTime> _Enrolled;
        partial void OnEnrolledChanging(Nullable<global::System.DateTime> value);
        partial void OnEnrolledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_ClassMeeting_Student", "ClassMeeting")]
        public EntityCollection<ClassMeeting> ClassMeetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Student", "ClassMeeting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassMeeting>("AttendanceModel.FK_ClassMeeting_Student", "ClassMeeting", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AttendanceModel", "FK_Registration_Student", "Registration")]
        public EntityCollection<Registration> Registrations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Registration>("AttendanceModel.FK_Registration_Student", "Registration");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Registration>("AttendanceModel.FK_Registration_Student", "Registration", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
